# Generated by Django 4.2.2 on 2023-06-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='recipient',
        ),
    ]
