# Generated by Django 4.2.2 on 2023-06-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_messages_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='roomname',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='roomname', to='chat.room'),
            preserve_default=False,
        ),
    ]
