# Generated by Django 4.2.2 on 2023-07-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_room_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='media/chatfiles'),
        ),
    ]
