# Generated by Django 4.2.2 on 2023-07-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_messages_docs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='docs',
            new_name='file',
        ),
    ]
