# Generated by Django 4.1.6 on 2023-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
