# Generated by Django 4.1.6 on 2023-05-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lprofile', '0003_posts_dislikes_posts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dbool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='lbool',
            field=models.IntegerField(default=0),
        ),
    ]
