# Generated by Django 4.1.6 on 2023-05-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lprofile', '0004_posts_dbool_posts_lbool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='dbool',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='lbool',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
    ]
