# Generated by Django 4.1.6 on 2023-05-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lprofile', '0007_posts_dislikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=300)),
            ],
        ),
    ]
