# Generated by Django 4.1.6 on 2023-05-02 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lprofile', '0008_profile1'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile1',
            name='profowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
