# Generated by Django 4.1.6 on 2023-05-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lprofile', '0010_alter_profile1_about_alter_profile1_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile1',
            name='about',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile1',
            name='firstname',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile1',
            name='lastname',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
