# Generated by Django 4.1.6 on 2023-05-03 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lprofile', '0011_alter_profile1_about_alter_profile1_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.ManyToManyField(related_name='connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
