# Generated by Django 4.1.6 on 2023-05-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lprofile', '0013_connections_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='connections',
        ),
    ]
