# Generated by Django 4.1.6 on 2023-05-03 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lprofile', '0014_delete_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile1',
            name='connection',
            field=models.ManyToManyField(related_name='connection', to=settings.AUTH_USER_MODEL),
        ),
    ]
