# Generated by Django 4.1.6 on 2023-05-05 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lprofile', '0015_profile1_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile1',
            name='connection',
            field=models.ManyToManyField(blank=True, related_name='connection', to=settings.AUTH_USER_MODEL),
        ),
    ]
