# Generated by Django 4.1.6 on 2023-05-09 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lprofile', '0017_remove_profile1_firstname_remove_profile1_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile1',
            old_name='connection',
            new_name='follower',
        ),
    ]
