# Generated by Django 4.1.6 on 2023-05-09 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lprofile', '0019_alter_profile1_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile1',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
