# Generated by Django 4.1.6 on 2023-05-10 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lprofile', '0021_profile1_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile1',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
