# Generated by Django 4.1.6 on 2023-05-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lprofile', '0022_profile1_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postimg',
            field=models.ImageField(blank=True, null=True, upload_to='postimages'),
        ),
        migrations.AddField(
            model_name='profile1',
            name='profimg',
            field=models.ImageField(blank=True, null=True, upload_to='profimages'),
        ),
    ]
