# Generated by Django 4.1.6 on 2023-05-13 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lprofile', '0024_alter_posts_postimg_alter_profile1_profimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('c_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_post', to='lprofile.posts')),
                ('comment_owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
