# Generated by Django 4.1.6 on 2023-05-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lprofile', '0025_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='replies',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
