# Generated by Django 4.1.6 on 2023-06-08 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lprofile', '0026_comments_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile1',
            name='role',
            field=models.CharField(default='neither', max_length=10),
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_title', models.CharField(max_length=50)),
                ('j_desc', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=50)),
                ('applicants', models.ManyToManyField(blank=True, related_name='seekers', to=settings.AUTH_USER_MODEL)),
                ('j_provider', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='j_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
