# Generated by Django 4.1.6 on 2023-06-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lprofile', '0027_profile1_role_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile1',
            name='role',
            field=models.CharField(default='Neither', max_length=10),
        ),
    ]
