# Generated by Django 4.2.2 on 2023-07-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lprofile', '0029_remove_comments_replies_comments_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile1',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='media/cvfiles'),
        ),
    ]
